### ISSUE TITLE
Running Separate Tracks at Different Speeds

### ISSUE THREAD

**Issue by AuzFox** [detomon/BlipKit#3]
Hello! Had a quick question regarding attaching multiple clocks to a context. I hope it's not too much trouble!
I'm trying to write a tracker similar to LSDJ in that each track can set its own play speed based on the tempo of the song. (For example, track A might run at 4 rows per beat while track B runs at 5 rows per beat)
I don't believe this is possible when only using the master clock, but I see that it's possible to attach multiple clocks to a context, so my thinking is to create one clock per track and use that to drive the divider callbacks.
Would this be the correct approach? If so, how would I set this up? If not, what would be the preferred method to accomplish this?

**Comment by detomon** [comment]
Hello @AuzFox

I think using multiple clocks for this situation is the right approach. You can use the clocks's callback directly without attaching dividers (it's still possible if needed with [BKDividerAttachToClock](https://github.com/detomon/BlipKit/blob/master/src/BKClock.h#L132)). I made a new example which shows this: <https://github.com/detomon/BlipKit/blob/master/examples/clocks.c> (I hope it's clear). This uses three clocks running with different periods which sync up every second. Technically, there is a drift between the clocks because of rounding errors, but it's minuscule and shouldn't be relevant.

**Comment by AuzFox** [comment]
Ah, this is just what I was looking for, and the example seems pretty clear to me on how it's working. Thanks a bunch! :)
By the way, sorry for not responding in the last issue I opened, but I appreciate the help for both issues!

**Comment by detomon** [comment]
No problem at all. Glad it helped!

**Comment by zyrup** [comment]
https://www.youtube.com/watch?v=kG_Ltc-j2N0
[https://www.bing.com/th?id=OVP.zjXRYXgMIYLP3v2ujT6k0wHgFo&pid=Api]<https://www.youtube.com/watch?v=kG_Ltc-j2N0>
I Played the HARDEST Skyblock<https://www.youtube.com/watch?v=kG_Ltc-j2N0>
In this video I play through the hardest skyblock map that is still posible in in hardcore mode. So no jumping off the island, no backups (to increase your chances with the wandering trader and to get iron shovels from zombies). With just 81 blocks to play around with you have to stretch minecraft to its limits to progress. This was truly an ...
www.youtube.com

________________________________
Von: Simon Schoenenberger ***@***.***>
Gesendet: Donnerstag, 7. September 2023 13:33
An: detomon/BlipKit ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [detomon/BlipKit] Running Separate Tracks at Different Speeds (Issue #3)


Closed #3<https://github.com/detomon/BlipKit/issues/3> as completed.

**Comment by zyrup** [comment]
https://www.youtube.com/watch?v=13XbgSx89mM
________________________________
Von: Simon Schoenenberger ***@***.***>
Gesendet: Donnerstag, 7. September 2023 13:33
An: detomon/BlipKit ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [detomon/BlipKit] Running Separate Tracks at Different Speeds (Issue #3)


Closed #3<https://github.com/detomon/BlipKit/issues/3> as completed.
